apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-local-prometheus-pvc
spec:
  storageClassName: local-storage-prometheus
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi